import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="mdl-js">
      <body className="antialiased font-sans">
        {children}
        <Toaster
          toastOptions={{
            style: {
              fontSize: "18px",
              padding: "16px 24px",
              fontWeight: "bold",
            },
          }}
        />
      </body>
    </html>
  );
}
